const metronomeTempos = {
  'Larghissimo': '20 bpm',
  'Adagissimo': '24 bpm',
  'Grave': '35 bpm',
  'Largo': '50 bpm',
  'Lento': '53 bpm',
  'Larghetto': '63 bpm',
  'Adagio': '71 bpm',
  'Adagietto': '75 bpm',
  'Marcia moderato': '84 bpm',
  'Andante': '92 bpm',
  'Andantino': '94 bpm',
  'Andante moderato': '95 bpm',
  'Moderato': '105 bpm',
  'Allegretto': '106 bpm',
  'Allegro moderato': '118 bpm',
  'Allegro': '138 bpm',
  'Vivace': '166 bpm',
  'Vivacissimo': '174 bpm',
  'Allegrissimo': '174 bpm',
  'Allegro vivace': '174 bpm',
  'Presto': '184 bpm',
  'Prestissimo': '205 bpm',
};
